<a href="https://colab.research.google.com/github/austinvanderlyn/Projects/blob/master/Aggregations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Summing the Values in an Array

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

46.14552208654325

In [3]:
np.sum(L)

46.14552208654323

In [4]:
big_array = np.random.rand(10000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1.65 ms ± 743 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
11.5 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Minimum and Maximum

In [5]:
min(big_array), max(big_array)

(1.3680585187025862e-05, 0.9997638713306572)

In [6]:
np.min(big_array), np.max(big_array)

(1.3680585187025862e-05, 0.9997638713306572)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

714 µs ± 31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.86 µs ± 2.18 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
print(big_array.min(), big_array.max(), big_array.sum())

1.3680585187025862e-05 0.9997638713306572 4994.619063109391


## Multi dimensional aggregates

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.65608642 0.31018646 0.40581125 0.01087383]
 [0.52980754 0.18602604 0.52636402 0.86139105]
 [0.34084111 0.30110011 0.76766416 0.44625312]]


In [10]:
M.sum()

5.34240511729975

In [11]:
M.min(axis=0)

array([0.34084111, 0.18602604, 0.40581125, 0.01087383])

In [12]:
M.max(axis=1)

array([0.65608642, 0.86139105, 0.76766416])