<a href="https://colab.research.google.com/github/austinvanderlyn/Projects/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 2: Numpy

In [1]:
import numpy
numpy.__version__

'1.22.4'

In [2]:
import numpy as np

A Python List Is More Than Just a List

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

Fixed Type Arrays in Python

In [7]:
import array
L = list(range(10))
A = array.array("i", L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import numpy as np

Creating Arrays From Python Lists

In [9]:
# integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [11]:
np.array([1, 2, 3, 4], dtype = "float32")

array([1., 2., 3., 4.], dtype=float32)

In [12]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays From Scratch

In [13]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype = "float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.89950775, 0.40861088, 0.23166231],
       [0.3761376 , 0.38734904, 0.58455005],
       [0.44041988, 0.54733278, 0.66933839]])

In [19]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.46579667, -0.80537687, -0.28694855],
       [-1.42462363,  0.12270304, -0.61562004],
       [-2.05543833, -0.03506579, -0.81167095]])

In [20]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 6, 4],
       [3, 0, 4],
       [5, 9, 2]])

In [21]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

NumPy Standard Data Types

In [23]:
np.zeros(10,
         dtype = "int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [24]:
np.zeros(10,
         dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

The Basics of NumPy Arrays

NumPy Array Attributes

In [25]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size = 6) # one-dimensional array
x2 = np.random.randint(10, size = (3, 4)) # two dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # three dimensional array

In [26]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [27]:
print("dtype:", x3.dtype)

dtype: int64


In [28]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [29]:
x1

array([5, 0, 3, 3, 7, 9])

In [30]:
x1[0]

5

In [31]:
x1[4]

7

In [32]:
x1[-1]

9

In [33]:
x1[-2]

7

In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[0,0]

3

In [36]:
x2[2,00]

1

In [37]:
x2[2,-1]

7

In [38]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [39]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

One Dimensional Subarrays

In [40]:
x = np.arange(10)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[0:5] # first five elements

array([0, 1, 2, 3, 4])

In [42]:
x[5:]  # elements after index 5s

array([5, 6, 7, 8, 9])

In [43]:
x[4:7]  #middle sub-array

array([4, 5, 6])

In [44]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [45]:
x[1::2]  # every other startinng at index 1

array([1, 3, 5, 7, 9])

In [46]:
x[1::-1]  #all auter, reverse

array([1, 0])

Multi Dimensional Subarrays

In [47]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [48]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [49]:
x2[:3, ::2] # All rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [50]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [51]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [52]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


In [53]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


Subarrays as no-copy views

In [54]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [55]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [56]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [57]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Creating Copies of Arrays

In [58]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [59]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [60]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [61]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [63]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [64]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [65]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

Concatenation of Arrays

In [66]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [67]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [68]:
# two dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [69]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
# concatenate along the second axis (zero - indexed)
np.concatenate([grid, grid],
               axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
# arrays of mixed dimensions
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Splitting of Arrays

In [73]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# The Slowness of Loops

In [77]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i] = 1.0 / values[i]
  return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [78]:
big_array = np.random.randint(1, 100, size = 10000000)
# %timeit compute_reciprocals(big_array)

# Introducing UFuncs

In [79]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [80]:
%timeit (1.0 / big_array)

59.3 ms ± 7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [81]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [82]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Exploring NumPy's UFuncs

## Array Arithmetic

In [84]:
x = np.arange(4)
print("x     =", x)
print("x = 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x     = [0 1 2 3]
x = 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [85]:
print("-x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)

-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [86]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [87]:
np.add(x, 2)

array([2, 3, 4, 5])